architect:
  - mkanev

docker:
  image: "frolvlad/alpine-oraclejdk8"

decrypt:
  settings.xml: "repo/settings.xml.asc"
  pubring.gpg: "repo/pubring.gpg.asc"
  secring.gpg: "repo/secring.gpg.asc"

merge:
  commanders:
    - mkanev
  script:
    - chmod a+x ./mvnw
    - ./mvnw clean install --errors --settings ../settings.xml

deploy:
  commanders:
    - mkanev
  script:
    - chmod a+x ./mvnw
    - ./mvnw clean deploy -Prultor --errors --settings ../settings.xml

release:
  commanders:
    - mkanev
  script:
    - chmod a+x ./scripts/version
    - chmod a+x ./mvnw
    - ./scripts/version ${tag}
    - git commit -am "${tag}"
    - ./mvnw clean deploy -Psonatype --errors --settings ../settings.xml
