architect:
  - mkanev
docker:
  image: "relateiq/oracle-java8"
decrypt:
  settings.xml: "repo/settings.xml.asc"
  pubring.gpg: "repo/pubring.gpg.asc"
  secring.gpg: "repo/secring.gpg.asc"
merge:
  script:
    - mvn clean install --errors --settings ../settings.xml
deploy:
  commanders:
    - mkanev
  script:
    - mvn clean deploy -Prultor --errors --settings ../settings.xml
release:
  commanders:
    - mkanev
  script:
    - chmod a+x ./scripts/version
    - chmod a+x ./mvnw
    - ./scripts/version ${tag}
    - git commit -am "${tag}"
    - mvn clean deploy -Psonatype --errors --settings ../settings.xml
