architect:
  - mkanev
decrypt:
  pubring.gpg: "repo/pubring.gpg.asc"
  secring.gpg: "repo/secring.gpg.asc"
  settings.xml: "repo/settings.xml.asc"
merge:
  script:
    - mvn clean install --errors --settings ../settings.xml
deploy:
  commanders:
    - mkanev
  script:
    - mvn clean deploy -Prultor --errors --settings ../settings.xml
release:
  commanders:
    - mkanev
  script:
    - ./scripts/version ${tag}
    - git commit -am "${tag}"
    - mvn clean deploy -Prelease-ossrh --errors --settings ../settings.xml
